### ISSUE TITLE
Linked project pages don't seem to work

### ISSUE THREAD

**Issue by jtth** [mlava/todoist-task-management#2]
When I try to link a project page in Roam with the project ID in my clipboard, the template gets created, but none of the tasks populate, and none of my created tasks in Roam get pushed to Todoist. No errors show up in the JS console, though. I'm using the Roam Depot plugin.

However, when I try to add a project that has no tasks, I get a notification in Roam that says there's nothing to add.

**Comment by mlava** [comment]
thanks for reporting and sorry for the trouble

looking into it!

**Comment by mlava** [comment]
I've found the bug and pushed a fix. It needs to be reviewed by the RR team and accepted before you are able to use again. Sorry for the trouble. @jtth

**Comment by jtth** [comment]
Thanks so much! 🙏🏼

**Comment by jtth** [comment]
This still doesn't seem to be working with the latest update.

**Comment by mlava** [comment]
@jtth 
Did it work at all between when we last discussed this and yesterday? I've made other changes since pushing the fix for this.
It's working on my end, with no errors in console.
Can you check the project page has the correct project id, in the form: `projectID: xxxxxxxxxx` where x is an integer and there are ten of them.
Also, could you open the browser console, usually with F12, clear it, then try to import project tasks. Then, post the console output here.
Thanks

**Comment by jtth** [comment]
No, project sync hasn't worked at all for me. 

Doing that the only output is `Creating project_id link` from `instrument.ts:124`. It adds the `projectID` bit at the bottom with the `hr` but doesn't add tasks from Todoist or sync anything. Nothing else in the output.

**Comment by mlava** [comment]
Once that happens, are you able to import via the command palette? It
should recognize the projectid and import the correct tasks...
I need to fix the project linking file, but haven't found the bug yet

**Comment by mlava** [comment]
Ok, sorry, I found the issue.
I've pushed a PR to the Roam team and hope they will review and accept it soon.
Thanks for reporting.

**Comment by jtth** [comment]
Thanks so much!

**Comment by jtth** [comment]
It doesn't seem to actually be syncing bidirectionally. If I mark a todo as done in Roam, it marks it as complete in Todoist, but new things added to Todoist don't get synced to the Roam project.

**Comment by mlava** [comment]
Hi again. Project-level sync isn't automatic. You will need to manually refresh each time you want to update. Only daily tasks work automatically at the moment.

If project auto-sync is important, I can think on how to implement, but I suspect it will be tricky. Perhaps a button that appears adjacent to the header that triggers a refresh would be enough?

**Comment by jtth** [comment]
Ah, okay. That makes some sense, but how do I trigger a sync instead of linking the project (where I have to copy the already-existing project ID to the clipboard then Link, which duplicates the previous tasks)?

**Comment by mlava** [comment]
You can just do Import Todoist tasks as it will recognise it's a project page

**Comment by jtth** [comment]
Ah, okay, thank you! That should do it!
